services:
  
  edge-service:
    build:
      context: edge-service/.
    container_name: edge-service
    env_file:
      - .env
    environment:
      - WATCHER_HOST=alert-watcher
    restart: always
    networks: 
      - inner-services

  alert-watcher:
    build:
      context: alert-watcher/.
    container_name: alert-watcher
    env_file:
      - .env
    environment:
      - WATCHER_RECEIVER_URL=http://edge-service:${PORT_STARTER}/api/v1/notify
      - TZ=Europe/Kyiv
    volumes:
      - ./config.yaml:/config.yaml
    init: true
    restart: always
    networks: 
      - inner-services

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    environment:
      - PORT_STARTER=${PORT_STARTER}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - inner-services
    depends_on:
      - edge-service

networks:
  inner-services:
    driver: bridge