services:
  
  edge-service:
    env_file:
      - .env
    image: ${EDGE_IMAGE:-lolman135/edge-service:latest}
    container_name: edge-service-${ENV:-main}
    environment:
      - WATCHER_HOST=alert-watcher
    restart: always
    networks: 
      - inner-services

  alert-watcher:
    env_file:
      - .env
    image: ${ALERT_WATCHER_IMAGE:-lolman135/alert-watcher:latest}
    container_name: alert-watcher-${ENV:-main}
    environment:
      - WATCHER_RECEIVER_URL=http://edge-service:${PORT_STARTER}/api/v1/notify
      - TZ=Europe/Kyiv
    volumes:
      - ./config.yaml:/config.yaml
    init: true
    restart: always
    networks: 
      - inner-services

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    ports:
      - '${NGINX_PORT}:80'
    environment:
      - PORT_STARTER=${PORT_STARTER}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - inner-services
    depends_on:
      - edge-service

networks:
  inner-services:
    driver: bridge