name: Master pipeline
on:
#  push:
#    branches:
#      - dev
  pull_request:
    branches:
      - master
    types: [closed]
  workflow_dispatch:
    inputs:
      environments:
        description: "Choose environment"
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build-workflow.yaml
    secrets: inherit

  call-deploy-dev-workflow:
    needs: call-build-workflow
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
      (github.event_name == 'workflow_dispatch' && inputs.environments == 'dev')
    uses: ./.github/workflows/deploy-dev-workflow.yaml
    secrets: inherit

  call-deploy-prod-workflow:
    needs: call-build-workflow
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/master') ||
      (github.event_name == 'workflow_dispatch' && inputs.environments == 'prod')
    uses: ./.github/workflows/deploy-prod-workflow.yaml
    secrets: inherit